// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtkpjnpqcceguhaicabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0a3BqbnBxY2NlZ3VoYWljYWJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzI1NjAsImV4cCI6MjA2NDA0ODU2MH0.0NeIUsF2uYhfweJjXVplcETZ145IqtvQU4IijYd0kKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);